export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const FETCH_RECIPES_REQUEST = "FETCH_RECIPES_REQUEST";
export const FETCH_RECIPES_SUCCESS = "FETCH_RECIPES_SUCCESS";
export const FETCH_RECIPES_FAILURE = "FETCH_RECIPES_FAILURE";

export const ADD_RECIPE_SUCCESS = "ADD_RECIPE_SUCCESS";
export const UPDATE_RECIPE_SUCCESS = "UPDATE_RECIPE_SUCCESS";
export const DELETE_RECIPE_SUCCESS = "DELETE_RECIPE_SUCCESS";
